# Generated by Django 5.2.6 on 2025-09-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='image_path',
            field=models.CharField(default='../images/not_found.png', max_length=500),
        ),
    ]
