# Generated by Django 5.2.6 on 2025-09-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0005_alter_portfolioimage_order_hobbyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='image',
        ),
    ]
