# Generated by Django 5.2.6 on 2025-11-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0006_remove_hobby_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbyimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='portfolioimage',
            name='image',
        ),
        migrations.AddField(
            model_name='hobbyimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
