# Generated by Django 5.2.6 on 2025-11-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0007_remove_hobbyimage_image_remove_portfolioimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='order',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
