# Generated by Django 5.2.6 on 2025-09-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Hobby Name')),
                ('description', models.TextField(verbose_name='Hobby Description')),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hobby Monthly cost')),
            ],
            options={
                'verbose_name': 'Hobby',
                'verbose_name_plural': 'Hobbies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Portfolio Name')),
                ('description', models.TextField(verbose_name='Portfolio Description')),
                ('portfolio_link', models.URLField(blank=True, null=True, verbose_name='Portfolio Link')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['name'],
            },
        ),
    ]
