# Generated by Django 5.2.6 on 2025-09-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0002_hobby_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='image_path',
        ),
        migrations.AddField(
            model_name='hobby',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hobbies/', verbose_name='Hobby Image'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolios/', verbose_name='Portfolio Image'),
        ),
    ]
