# Generated by Django 5.2.6 on 2025-09-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0003_remove_hobby_image_path_hobby_image_portfolio_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolios/')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='PortfolioDatabase.portfolio')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
