# Generated by Django 5.2.6 on 2025-09-20 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0004_remove_portfolio_image_portfolioimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='HobbyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hobbies/')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=2)),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='PortfolioDatabase.hobby')),
            ],
        ),
    ]
